### ISSUE TITLE
Cannot get data using javascript tooltips in deck.gl screen grid

### ISSUE THREAD

**Issue by Riskatri** [apache/superset#20266]
#### How to reproduce the bug

1. Go to maps deck.gl screen grid 
2. Write code javascript in javacript tooltips generator  
Example :
Function getData(d) {
 d.object.extraProps[0].data.map(i, x => console.log(x)) }
4. Run code
5. See errror : data.map is not a function.
When log data d in function, i cannot see the data object
    
How to use javascript tooltips generator for get data from my field ?

### Environment

Superset version 1.5.0

**Comment by rusackas** [comment]
I think most users have the JS Tooltips feature turned off because of the security risks (perhaps not too scary of a risk, but a risk nonetheless). It might be worth digging back into a (very) old Superset SHA and seeing if you can find a working state for this feature. If you can, it's just a matter of `git bisect` to figure out where things might have gone sideways.

**Comment by rusackas** [comment]
If you are able to find an older version/SHA where this worked, I might be able to help you with the diagnostic part.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
