### ISSUE TITLE
Superset 1.3.0 add new database returns 500

### ISSUE THREAD

**Issue by grafke** [apache/superset#16492]
Adding a new database does not work on Superset 1.3.0 (After an upgrade from 1.2.0)
Stacktrace:
```Unable to load dialect <class 'sqlalchemy.dialects.mssql.adodbapi.MSDialect_adodbapi'>: type object 'MSDialect_adodbapi' has no attribute 'dbapi'
2021-08-28 11:15:02,478:WARNING:superset.db_engine_specs:Unable to load dialect <class 'sqlalchemy.dialects.mssql.adodbapi.MSDialect_adodbapi'>: type object 'MSDialect_adodbapi' has no attribute 'dbapi'
module 'sqlalchemy_clickhouse.base' has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 67, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/views/base_api.py", line 85, in wraps
    raise ex
  File "/usr/local/lib/python3.8/site-packages/superset/views/base_api.py", line 82, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/utils/core.py", line 1428, in time_function
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/utils/log.py", line 241, in wrapper
    value = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/databases/api.py", line 923, in available
    for engine_spec, drivers in get_available_engine_specs().items():
  File "/usr/local/lib/python3.8/site-packages/superset/db_engine_specs/__init__.py", line 130, in get_available_engine_specs
    backend = dialect.name
AttributeError: module 'sqlalchemy_clickhouse.base' has no attribute 'name'
2021-08-28 11:15:02,486:ERROR:superset.views.base:module 'sqlalchemy_clickhouse.base' has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 67, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/views/base_api.py", line 85, in wraps
    raise ex
  File "/usr/local/lib/python3.8/site-packages/superset/views/base_api.py", line 82, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/utils/core.py", line 1428, in time_function
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/utils/log.py", line 241, in wrapper
    value = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/databases/api.py", line 923, in available
    for engine_spec, drivers in get_available_engine_specs().items():
  File "/usr/local/lib/python3.8/site-packages/superset/db_engine_specs/__init__.py", line 130, in get_available_engine_specs
    backend = dialect.name
AttributeError: module 'sqlalchemy_clickhouse.base' has no attribute 'name'
```

### Expected results

Ability to add new databases.

### Actual results

A call to /api/v1/database/available/ returns:
{"errors": [{"message": "module 'sqlalchemy_clickhouse.base' has no attribute 'name'", "error_type": "GENERIC_BACKEND_ERROR", "level": "error", "extra": {"issue_codes": [{"code": 1011, "message": "Issue 1011 - Superset encountered an unexpected error."}]}}]}

#### Screenshots

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/9698688/131216048-a17d2001-d733-45c5-9f69-2005381dbacd.png">

#### How to reproduce the bug

1. Go to /databaseview/list/
2. Open developer console
2. Click on + Database

### Environment

(please complete the following information):

- superset version: 1.3.0
- python version: 3.8.11
- node.js version: 14
- any feature flags active:  N/A
- sqlalchemy-clickhouse==0.1.5.post0
- infi.clickhouse-orm==1.0.2

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Quickfix

After removing the following libs, the +Database continues to work. However, superset 1.2.0 used to work with the same libs just fine.
- sqlalchemy-clickhouse==0.1.5.post0
- infi.clickhouse-orm==1.0.2

**Comment by villebro** [comment]
Have you tried `clickhouse-sqlalchemy` You seem to be running `sqlalchemy-clickhouse` which some have said to not work as well, so switching the connector might help.

**Comment by machzqcq** [comment]
I can confirm that uninstalling `sqlalchemy-clickhouse` and installing `clickhouse-sqlalchemy` disappears the reported UI error. Tried on ubuntu 20.04. Here are the steps
```
pip3 uninstall sqlalchemy-clickhouse
pip3 install wheel. # if you get error on setup.py and not able to bdist_wheel ~ish
pip3 install clickhouse-sqlalchemy
```

**Comment by villebro** [comment]
Thanks for confirming - closing

**Comment by grafke** [comment]
Thanks!
