### ISSUE TITLE
FAB 5.0 compatibility related bugs in 6.0.0rc4

### ISSUE THREAD

**Issue by diegoscarabelli** [apache/superset#36549]
## TL;DR

Superset 6.0.0rc4 has **incomplete Flask-AppBuilder 5.0.0 compatibility**. While FAB 5.0.0 is included in requirements, critical API incompatibilities prevent successful deployment.

**Verified against commit**: `6a1c30e5e7` (6.0.0rc4 release)

---

### Issue #1: Flask-SQLAlchemy 2.5.1 Incompatibility

**Error**:
```
SignallingSession.get_bind() got an unexpected keyword argument 'bind'
```

**Location**: Runtime, during database operations

**Root Cause**:
- Flask-AppBuilder 5.0.0 requires Flask-SQLAlchemy 3.x for proper SQLAlchemy 1.4 compatibility
- Superset 6.0.0rc4 pins Flask-SQLAlchemy==2.5.1 in `requirements/base.txt:137`
- This creates a `get_bind()` API incompatibility between Flask-SQLAlchemy 2.x and SQLAlchemy 1.4

**Solution**:

Update `pyproject.toml` to require Flask-SQLAlchemy 3.x:
```toml
[project]
dependencies = [
    # ... other deps ...
    "flask-sqlalchemy>=3.0.0,<4.0",
]
```

Then regenerate requirements:
```bash
pip-compile pyproject.toml requirements/base.in -o requirements/base.txt
pip-compile requirements/development.in -c requirements/base.txt -o requirements/development.txt
```

**Impact**: 🔴 CRITICAL - Prevents application from starting

---

### Issue #2: Removed FAB 5.0 API - `sync_role_definitions()`

**Error**:
```python
AttributeError: 'SupersetSecurityManager' object has no attribute 'sync_role_definitions'
```

**Location**: `superset/cli/main.py:85`

**Root Cause**:
Flask-AppBuilder 5.0.0 removed the `SecurityManager.sync_role_definitions()` method. The 6.0.0rc4 code still calls this removed method during initialization.

**Verification**:
```bash
$ grep -n "sync_role_definitions" /path/to/6.0.0rc4/superset/cli/main.py
85:    security_manager.sync_role_definitions()
```

**Solution**:

Add compatibility shim in `superset/cli/main.py`:

```python
def init() -> None:
    """Inits the Superset application"""
    appbuilder.add_permissions(update_perms=True)

    # FAB 5.0.0 removed sync_role_definitions()
    # Permissions are already synced by add_permissions(update_perms=True)
    if hasattr(security_manager, 'sync_role_definitions'):
        # FAB < 5.0.0
        security_manager.sync_role_definitions()
    # FAB >= 5.0.0: No action needed, permissions already synced
```

**Alternative Solution**: Remove the call entirely, as `add_permissions(update_perms=True)` already handles role definition syncing in FAB 5.0.0.

**Impact**: 🔴 CRITICAL - Prevents `superset init` from completing

---

### Using Docker (Recommended)

1. Clone Superset and checkout 6.0.0rc4:
```bash
git clone https://github.com/apache/superset.git
cd superset
git checkout 6a1c30e5e7  # 6.0.0rc4
```

2. Attempt to initialize:
```bash
docker compose up superset-init
```

3. Observe failures:
   - Issue #1: `get_bind()` errors during database operations
   - Issue #2: `AttributeError` on `sync_role_definitions()`

### Using Local Installation

1. Install Superset 6.0.0rc4:
```bash
pip install apache-superset==6.0.0rc4
```

2. Initialize database:
```bash
superset db upgrade
superset init
```

3. Observe `AttributeError: 'SupersetSecurityManager' object has no attribute 'sync_role_definitions'`

---

## Environment Details

**Working Configuration** (what 6.0.0rc4 needs):
- Flask-AppBuilder: 5.0.0
- Flask-SQLAlchemy: 3.0.5+ (or any 3.x)
- SQLAlchemy: 1.4.54

**Current 6.0.0rc4 Configuration** (broken):
- Flask-AppBuilder: 5.0.0 ✅
- Flask-SQLAlchemy: 2.5.1 ❌ (should be 3.x)
- SQLAlchemy: 1.4.54 ✅

---

### Priority 1: Update Flask-SQLAlchemy Requirement

**File**: `pyproject.toml`

```diff
[project]
dependencies = [
    # ... other dependencies ...
+   "flask-sqlalchemy>=3.0.0,<4.0",
    # ... other dependencies ...
]
```

**File**: `requirements/base.txt` (regenerated from pyproject.toml)

```diff
- flask-sqlalchemy==2.5.1
+ flask-sqlalchemy==3.0.5  # (or latest 3.x)
```

### Priority 2: Fix sync_role_definitions() Call

**File**: `superset/cli/main.py`

**Option A** (Backward compatible):
```python
def init() -> None:
    """Inits the Superset application"""
    appbuilder.add_permissions(update_perms=True)

    # Handle FAB 4.x and 5.x compatibility
    if hasattr(security_manager, 'sync_role_definitions'):
        security_manager.sync_role_definitions()
```

**Option B** (Clean, FAB 5.0+ only):
```python
def init() -> None:
    """Inits the Superset application"""
    # FAB 5.0.0+ handles role definitions in add_permissions()
    appbuilder.add_permissions(update_perms=True)
```

---

## Related Issues & PRs

- **FAB 5.0 Upgrade PR**: https://github.com/apache/superset/pull/33055
- **FAB 5.0.0 Release Notes**: https://github.com/dpgaspar/Flask-AppBuilder/releases/tag/v5.0.0
- **FAB Migration Guide**: https://flask-appbuilder.readthedocs.io/en/latest/versionmigration.html#migrating-to-5-0-0
- **Flask-SQLAlchemy 3.x Changes**: https://flask-sqlalchemy.palletsprojects.com/en/3.1.x/changes/#version-3-0-0

---

## Testing Checklist

After applying fixes, verify:

- [ ] `docker compose up superset-init` completes without errors
- [ ] Database migrations run successfully
- [ ] Admin user is created
- [ ] Roles and permissions are initialized
- [ ] Example data loads (if using examples)
- [ ] Application starts and is accessible at http://localhost:8088
- [ ] Login works with created admin credentials

---

### Why Flask-SQLAlchemy 3.x is Required

FAB 5.0.0 was updated to use SQLAlchemy 1.4+ features that require Flask-SQLAlchemy 3.x for proper integration. The main issue is the `get_bind()` method signature change:

- **Flask-SQLAlchemy 2.x**: `get_bind(mapper=None, clause=None, bind=None)`
- **Flask-SQLAlchemy 3.x**: `get_bind(mapper=None, clause=None)` (removed `bind` parameter)

SQLAlchemy 1.4 calls `get_bind()` without the `bind` parameter, which Flask-SQLAlchemy 2.x doesn't support.

### Why sync_role_definitions() Was Removed

In FAB 5.0.0, the role definition syncing logic was consolidated into the `add_permissions()` method when called with `update_perms=True`. The separate `sync_role_definitions()` method became redundant and was removed.

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sfirke** [comment]
Thanks @diegoscarabelli . I wonder if/why this does not affect the route of deploying the docker image 6.0.0rc4 - that worked fine for me. @dosu should this affect deploying with docker compose up using the apache/superset:6.0.0rc4 image, why or why not compared to the docker deployment steps that are described in the bug report?

**Comment by sfirke** [comment]
@diegoscarabelli I tried following the instructions for [deploying a release with Docker Compose](https://superset.apache.org/docs/installation/docker-compose/#option-4---boot-up-an-official-release) and ran:
```bash
~/git/superset$ export TAG=6.0.0rc4
~/git/superset$ git checkout $TAG
Note: switching to '6.0.0rc4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 6a1c30e5e7 chore: update changelog for 6.0.0rc4

~/git/superset$ docker compose -f docker-compose-image-tag.yml up
```

And it seemed to work fine out of the box, there were no errors in the logs as the application started up. `superset_init` exited with success:
```
superset_init   | Init Step 4/4 [Complete] -- Loading examples
superset_init   | ######################################################################
superset_init exited with code 0
```

I won't ping the bot anymore, I don't think it's being helpful. Hopefully a human who understands your report better than I do can reconcile what's going on.

**Comment by martyngigg** [comment]
I don't know if this might be the problem but I find I occasionally get random `superset-init` service failures when I haven't run `docker compose up --build` for a while. I think I first observed this when the `superset_core` package was introduced but it wasn't built into the image and `-init` fell over. It might be a red herring but thought I'd leave this here just in case.

**Comment by diegoscarabelli** [comment]
Apologies for the false alarm. I tried again to reproduce the bugs and realized that they were in both cases artifacts. However, it does point out that Superset currently would have an incompatibility problem if the full `get_bind()` function signature is utilized in the future, and if the custom `sync_role_definitions()` is removed. 

 Here a detailed debug of what happened. 

# The FAB 5.0 Bugs Were Not Reproduced

**TL;DR**: The documented FAB 5.0 compatibility bugs do not exist. Superset 6.0.0rc4 work correctly with Flask-SQLAlchemy 2.5.1 + Flask-AppBuilder 5.0.0. The bugs I reported were in reality theoretical incompatibilities misinterpreted as bugs. 

## `get_bind()` Error - Why It Doesn't Occur

### The Documented Bug

```
SignallingSession.get_bind() got an unexpected keyword argument 'bind'
```

### Why It Was Expected 

- Flask-SQLAlchemy 2.5.1: `get_bind(mapper, clause)`
- SQLAlchemy 1.4: `get_bind(mapper, clause, bind=None)`
- Signature mismatch exists on paper

### Why It Doesn't Happen

SQLAlchemy 1.4 doesn't pass the `bind` parameter in Superset's code paths.

```python
# Flask-SQLAlchemy 2.5.1 implementation
def get_bind(self, mapper=None, clause=None):
    # ... handles binding logic
    return SessionBase.get_bind(self, mapper, clause)  # Calls parent without bind
```

When SQLAlchemy 1.4 calls `get_bind()` in the operations Superset uses:
- It calls with `(mapper, clause)`
- It does NOT pass the optional `bind` keyword argument
- Flask-SQLAlchemy 2.5.1 handles it correctly

### Why Reported Bug Previously

While building on top of 6.0.0rc4, the call of the Superset use of get_bind() was modified to include the bind parameter, due to the function signature in SQLAlchemy 1.4. This caused the error to appear in that specific context. However, in vanilla 6.0.0rc4, Superset's code paths do not trigger this issue.

### Conclusions
The theoretical incompatibility doesn't manifest in practice. However, this is something to keep in mind for future versions. 

---

## Missing `sync_role_definitions()` - Why It Doesn't Occur

### The Documented Bug

```python
AttributeError: 'SupersetSecurityManager' object has no attribute 'sync_role_definitions'
```

### Why It Was Expected

- Flask-AppBuilder 5.0.0 removed `SecurityManager.sync_role_definitions()`
- Superset calls `security_manager.sync_role_definitions()` in `cli/main.py:85`

### Why It Doesn't Happen

**Superset has its own implementation** - not inherited from FAB.

```python
# superset/security/manager.py:1175
class SupersetSecurityManager(SecurityManager):
    def sync_role_definitions(self) -> None:
        """Initialize the Superset application with security roles and such."""
        logger.info("Syncing role definition")
        self.create_custom_permissions()
        pvms = self._get_all_pvms()
        self.set_role("Admin", self._is_admin_pvm, pvms)
        self.set_role("Alpha", self._is_alpha_pvm, pvms)
        self.set_role("Gamma", self._is_gamma_pvm, pvms)
        self.set_role("sql_lab", self._is_sql_lab_pvm, pvms)
        # ... continues
```

This method:
- Exists in Superset's own `SupersetSecurityManager` class
- Is NOT inherited from FAB's base `SecurityManager`
- Works with both FAB 4.x and FAB 5.x

FAB 5.0's removal of this method doesn't affect Superset.

### Why Reported Bug Previously

In my modification to 6.0.0rc4, Claude found the repetition and removed the custom function implementation in Superset, leading to the error. However, in vanilla 6.0.0rc4, the method is present and works correctly.

### Conclusions

The removal of `sync_role_definitions()` from FAB 5.0 does not impact Superset, as it implements its own version of the method.

---

## Flask-AppBuilder 5.0 Dependency Facts

### What FAB 5.0 Actually Requires
```python
# From Flask-AppBuilder 5.0.0 package metadata
"Flask-SQLAlchemy>=2.4.0,<4"
```

This means FAB 5.0 accepts BOTH:
- Flask-SQLAlchemy 2.x (2.4.0 - 2.5.1)
- Flask-SQLAlchemy 3.x (3.0.0 - 3.1.x)

**Comment by sfirke** [comment]
Okay, thanks so much for the follow-up. Sounds like the problem was your modifications of the codebase and not with vanilla Superset 6.0.0rc4. I'm going to close this issue, accordingly; if you feel there is something that still needs to be addressed let's discuss further and maybe open a new, clean issue.
