### ISSUE TITLE
Superset 2.0.0rc1 not working in Chrome 71.0.3578.98

### ISSUE THREAD

**Issue by KMoszczyc** [apache/superset#21060]
Superset 2.0.0rc1 is not working in Chrome Version 71.0.3578.98 (Official Build) (64-bit) via docker deployment. By not working I mean after login it's showing the loading animation indefinetly. I don't have latest version installed because I get errors when I try to setup Dremio connection in Superset (some sort of builtin.nonetype error).

With error 'Object.fromEntries is not a function' that occurs in .src/utils/parseCookies.ts

#### How to reproduce the bug

1. Install Chrome Version 71.0.3578.98
2. Install Superset 2.0.0rc1 with docker
3. Login
4. Wait...

### Expected results

Normally working Superset page.
![image](https://user-images.githubusercontent.com/61971053/184146735-d2331263-1012-46e9-89df-e73f21f2c331.png)

### Actual results

Indefinete loading.
![image](https://user-images.githubusercontent.com/61971053/184144368-b5d70a53-4c9b-42df-a576-478fb20d2b44.png)

### Environment

- browser type and version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- superset version: `2.0.0rc1`
- python version: `Python 3.8.12`
- node.js version: ```bash: node: command not found```
- any feature flags active:

### Additional context
- It works just fine in Firefox and Edge browsers.
- Also it's worth to mention that old Superset versions work fine in that Chrome version - Superset 1.3.2 or 1.2.0.
- I can't update Chrome Version as it's being accessed via corporate Citrix Workspace :(

**Comment by sfirke** [comment]
This can probably be closed now that 2.0.0 was released months ago.

**Comment by rusackas** [comment]
Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps. Thank you for understanding :)

**Comment by KMoszczyc** [comment]
I no longer work there so whatever 🦥
