### ISSUE TITLE
Helper formatDate stopped working in Handlebars charts since 4.1.2 update

### ISSUE THREAD

**Issue by goldjee** [apache/superset#32960]
### Bug description

We have updated our installation from 4.0.2 to 4.1.2 today. All the Handlebars charts that use `formatDate` helper started throwing `i is not a function` error.

Steps to reproduce:
1. Create a new dataset with one value.
```SQL
select '2025-04-01'::timestamp as t
```
2. Create a new Handlebars chart from this dataset.
3. Add `t` column to the columns list and hit "Create chart" button. The chart renders normally.

<img width="1056" alt="Image" src="https://github.com/user-attachments/assets/553445fe-5c9b-41ce-bb2b-05403b18037a" />

4. Modify template as follows:
```HTML
<ul class="data-list">
    {{#each-data}}
        <li>{{formatDate 'DD.MM.YYYY' t}}</li>
    {{/each}}
</ul>
```
5. Now the chart preview renders the error.

<img width="1046" alt="Image" src="https://github.com/user-attachments/assets/0a5395ce-02f4-4300-bce5-5e8d454fa721" />

### Superset version

4.1.2

### Python version

3.11

### Node version

I don't know

### Browser

Chrome

### Additional context

There are no related errors present either in the browser console or server logs.

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
Sorry, this one has slipped under the radar, and it does appear to be an issue in current `master`

**Comment by rusackas** [comment]
I opened a  PR to test and fix this. Please review.
