### PR TITLE
fix(handlebars): register a dayjs-backed formatDate helper (#32960)

### LINKED ISSUE #32960: Helper formatDate stopped working in Handlebars charts since 4.1.2 update
### Bug description

We have updated our installation from 4.0.2 to 4.1.2 today. All the Handlebars charts that use `formatDate` helper started throwing `i is not a function` error.

Steps to reproduce:
1. Create a new dataset with one value.
```SQL
select '2025-04-01'::timestamp as t
```
2. Create a new Handlebars chart from this dataset.
3. Add `t` column to the columns list and hit "Create chart" button. The chart renders normally.

Image

4. Modify template as follows:
```HTML
<ul class="data-list">
    {{#each-data}}
        <li>{{formatDate 'DD.MM.YYYY' t}}</li>
    {{/each}}
</ul>
```
5. Now the chart preview renders the error.

Image

### Screenshots/recordings

_No response_

### Superset version

4.1.2

### Python version

3.11

### Node version

I don't know

### Browser

Chrome

### Additional context

There are no related errors present either in the browser console or server logs.

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY

Fixes #32960: the `formatDate` Handlebars helper stopped working after 4.1.2. A template such as `{{formatDate 'DD.MM.YYYY' t}}` rendered **"i is not a function"** (minified) / **"moment is not a function"** (dev build) instead of the formatted date.

**Root cause:** `formatDate` is provided by the `just-handlebars-helpers` library, whose implementation resolves moment lazily:

```js
var moment = global.moment;
if (!moment) moment = require('moment/min/moment-with-locales');
```

`HandlebarsViewer` switched from moment to **dayjs**, so neither `global.moment` nor a bundled `moment/min/moment-with-locales` exists in the production bundle. The lazy lookup yields a non-callable value, surfaced (minified) as *"i is not a function"*.

**Fix:** register a small **dayjs-backed `formatDate` override** in `HandlebarsViewer`, *after* `Helpers.registerHelpers(Handlebars)` so it wins, preserving the original `{{formatDate formatString date [locale]}}` signature. This keeps existing templates working without pulling moment back into the bundle. dayjs is already the date library used by the sibling `dateFormat` helper in the same file.

Because the failure is a bundling/minification artifact, it does **not** reproduce in a Jest unit test (Node's `require('moment/...')` resolves fine), which is why the regression guard is a Playwright **E2E** test.

### BEFORE/AFTER

**Before:** a Handlebars chart using `{{formatDate 'DD.MM.YYYY' ds}}` renders `i is not a function` / `moment is not a function`.

**After:** the same chart renders the formatted date (e.g. `01.01.2008`).

### TESTING INSTRUCTIONS

```bash
cd superset-frontend
npx playwright test playwright/tests/chart/handlebars-format-date.spec.ts
```

The spec creates a Handlebars chart whose template uses `{{formatDate 'DD.MM.YYYY' ds}}`, opens it in Explore, and asserts it renders a `DD.MM.YYYY` date and does **not** render a "... is not a function" error.

### ADDITIONAL INFORMATION

- [x] Has associated issue: closes #32960
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+ * CI red   => the bug is still live; the fix belongs in the Handlebars plugin
+ *             (superset-frontend/plugins/plugin-chart-handlebars), e.g. by
+ *             providing a moment-free formatDate or making moment resolvable.
+ */
+import { testWithAssets, expect } from '../../helpers/fixtures';
+import { apiPost } from '../../helpers/api/requests';
+
+const DATASET_NAME = 'birth_names';
+
+async function findDatasetIdByName(page: any, name: string): Promise<number> {
```
[the remark this answers is not in the document]
Comment (rusackas) [reply superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts]: Good catch — replaced `page: any` with the properly typed `Page` from `@playwright/test`. Pushed in eb2ba20066.

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+ *
+ * This is a TDD validation test. It creates a Handlebars chart whose template
+ * uses `{{formatDate 'DD.MM.YYYY' ds}}` and asserts the chart renders a real
+ * formatted date rather than the helper error.
+ *
+ * CI green => formatDate works again; merging closes #32960.
+ * CI red   => the bug is still live; the fix belongs in the Handlebars plugin
+ *             (superset-frontend/plugins/plugin-chart-handlebars), e.g. by
+ *             providing a moment-free formatDate or making moment resolvable.
+ */
```
Comment (sadpandajoe) [inline superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts:34]: nit: this d=probably doesn't need to be in the file

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+  if (!body.result?.length) {
+    throw new Error(`Dataset ${name} not found`);
+  }
+  return body.result[0].id;
+}
+
+testWithAssets(
+  'Handlebars formatDate helper renders a formatted date (#32960)',
+  async ({ page, testAssets }) => {
+    const datasetId = await findDatasetIdByName(page, DATASET_NAME);
```
[the remark this answers is not in the document]
Comment (rusackas) [reply superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts]: Good calls on both. Bumped this test to `TIMEOUT.SLOW_TEST` since it chains the dataset lookup, chart creation, and Explore render, and swapped the inline dataset lookup for the existing `getDatasetByName` helper (which already uses `rison.encode`). Pushed in 5be8142f7d.

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts (hunk 2 above)
Comment (rusackas) [reply superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts:34]: Agreed — trimmed that big rationale block down to a couple of lines pointing at the issue and the plugin. Pushed in 5be8142f7d.

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+      params: JSON.stringify(params),
+    });
+    expect(chartResp.ok()).toBe(true);
+    const chartId: number = (await chartResp.json()).id;
+    testAssets.trackChart(chartId);
+
+    await page.goto(`explore/?slice_id=${chartId}`);
+    await page.waitForSelector('[data-test="datasource-control"]', {
+      timeout: 30_000,
+    });
```
Comment (sadpandajoe) [inline superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts]: Nit: I think it's ok to not have an explore page object right now as we aren't doing too much with it, but we should probably not hardcode the timeout and instead set a timeout variable. Maybe the page load one?

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+
+    const panel = page.locator('[data-test="chart-container"]');
+    await panel.waitFor({ state: 'visible', timeout: 30_000 });
```
Comment (sadpandajoe) [inline superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts]: nit: same as above, we should just set this as a variable

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts [hunk 6]
```diff
@@ -0,0 +1,90 @@
...
+
+    // The helper error surfaces as a "... is not a function" message rendered
+    // in place of the chart content.
+    await expect(panel).not.toContainText('is not a function', {
+      timeout: 20_000,
```
Comment (sadpandajoe) [inline superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts]: nit: same here. probably set this as a variable.

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts [hunk 7]
```diff
@@ -0,0 +1,90 @@
...
+    });
+
+    // At least one list item should contain a DD.MM.YYYY formatted date.
+    await expect(panel.locator('li.hb-item').first()).toHaveText(
+      /\d{2}\.\d{2}\.\d{4}/,
+      { timeout: 20_000 },
```
Comment (sadpandajoe) [inline superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts]: nit: should be a variable here too.

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts [hunk 8]
```diff
@@ -0,0 +1,90 @@
...
+      styleTemplate: '',
+    };
+
+    const chartResp = await apiPost(page, 'api/v1/chart/', {
+      slice_name: `handlebars_format_date_${Date.now()}`,
+      viz_type: 'handlebars',
+      datasource_id: datasetId,
+      datasource_type: 'table',
+      params: JSON.stringify(params),
+    });
```
Comment (sadpandajoe) [inline superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts]: Can this not be replaced with `apiPostChart` from `superset-frontend/playwright/helpers/api/chart.ts`

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts [hunk 9]
```diff
@@ -0,0 +1,90 @@
...
+    expect(chartResp.ok()).toBe(true);
+    const chartId: number = (await chartResp.json()).id;
+    testAssets.trackChart(chartId);
+
+    await page.goto(`explore/?slice_id=${chartId}`);
```
Comment (sadpandajoe) [inline superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts]: Looks like we do have an explore page object at `superset-frontend/playwright/pages/ExplorePage.ts` that you can probably build a `goto` function where you pass it a `chartId`

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts [hunk 10]
```diff
@@ -0,0 +1,90 @@
...
+    await page.waitForSelector('[data-test="datasource-control"]', {
```
Comment (sadpandajoe) [inline superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts]: can probably use the `waitForPageLoad` function for the page object.

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts [hunk 11]
```diff
@@ -0,0 +1,90 @@
...
+
+    const chartResp = await apiPost(page, 'api/v1/chart/', {
+      slice_name: `handlebars_format_date_${Date.now()}`,
+      viz_type: 'handlebars',
+      datasource_id: datasetId,
+      datasource_type: 'table',
+      params: JSON.stringify(params),
+    });
+    expect(chartResp.ok()).toBe(true);
+    const chartId: number = (await chartResp.json()).id;
```
[the remark this answers is not in the document]
Comment (rusackas) [reply superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts]: Good catch — the chart-creation response can come back either as `{ id }` or wrapped as `{ result: { id } }`. Switched to `apiPostChart`, parse `body.result?.id ?? body.id`, and added an explicit `expect(chartId).toBeTruthy()` so it fails loudly rather than navigating to `slice_id=undefined` or tracking an undefined chart for cleanup. Pushed in 003f292dec.

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts (hunk 4 above)
Comment (rusackas) [reply superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts]: Good call — replaced the hardcoded `30_000` here with the `TIMEOUT.PAGE_LOAD` constant (the wait now goes through `ExplorePage.waitForPageLoad`). Pushed in 003f292dec.

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts (hunk 5 above)
Comment (rusackas) [reply superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts]: Done — this now uses a `TIMEOUT` constant instead of a magic number. Pushed in 003f292dec.

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts (hunk 6 above)
Comment (rusackas) [reply superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts]: Done — swapped the magic number for a `TIMEOUT` constant (`TIMEOUT.API_RESPONSE`). Pushed in 003f292dec.

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts (hunk 7 above)
Comment (rusackas) [reply superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts]: Done — this one is a `TIMEOUT` constant now too. Pushed in 003f292dec.

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts (hunk 8 above)
Comment (rusackas) [reply superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts]: Yes — switched to `apiPostChart` from `playwright/helpers/api/chart.ts`. Pushed in 003f292dec.

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts (hunk 9 above)
Comment (rusackas) [reply superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts]: Good idea — added a `goto(chartId)` helper to `ExplorePage` that navigates to `explore/?slice_id=<id>` and then calls `waitForPageLoad`, and the test uses it now. Pushed in 003f292dec.

File: superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts (hunk 10 above)
Comment (rusackas) [reply superset-frontend/playwright/tests/chart/handlebars-format-date.spec.ts]: Done — `ExplorePage.goto` delegates to `waitForPageLoad`, so the test relies on the page object for the load wait instead of an inline `waitForSelector`. Pushed in 003f292dec.

**Review by aminghadersohi — COMMENTED** [review]
**PR #40817 — review @ 4ca1d338966f7680ed098275247d5dfb32fd8d8c**

---

### Prior threads: status at HEAD

All concerns raised by sadpandajoe, copilot, bito, and codeant appear resolved across the four follow-up commits:

| Thread | Resolved in |
|--------|------------|
| `page: any` → `Page` type | eb2ba20066 |
| Test timeout bumped to `TIMEOUT.SLOW_TEST` (60 s) | 5be8142f7d |
| `getDatasetByName` helper reused; large comment trimmed | 5be8142f7d |
| All magic timeout numbers replaced with `TIMEOUT.*` constants | 003f292dec |
| Switched to `apiPostChart` from `playwright/helpers/api/chart.ts` | 003f292dec |
| Both `{ id }` and `{ result: { id } }` response shapes handled; explicit `toBeTruthy()` guard | 003f292dec |
| `ExplorePage.goto(chartId)` helper added and used | 003f292dec |
| `waitForPageLoad` delegated to page object | 003f292dec |

---

### New findings

**MEDIUM — `instance.locale(localeString)` silently falls back to English**
`HandlebarsViewer.tsx` line 132

```ts
? instance.locale(localeString).format(format)
```

dayjs's instance `.locale()` only switches locale if the locale file has already been imported (e.g., `import 'dayjs/locale/fr'`). `extendedDayjs` (imported at line 22) extends the plugins but loads only the English locale. A template author who writes `{{formatDate 'MMMM YYYY' ds 'fr'}}` expecting "juin 2024" will get "June 2024" with no error or warning — not even from the `localizedFormat` tokens that `L`, `LL`, etc. expand into.

The three-argument signature is documented in the comment above the helper and in `just-handlebars-helpers` docs, so users will try it. Consider one of:
- A code comment beside line 132 noting that only the `'en'` locale is available until additional locale files are imported.
- `if (localeString !== 'en') throw new Error(\`formatDate: locale '${localeString}' is not loaded; only 'en' is available by default\`)` — this at least produces a visible error rather than silent wrong output.
- Lazily import a locale bundle (heavy, probably not worth it for a chart plugin).

---

**LOW — `||` coerces falsy timestamp `0` to current date**
`HandlebarsViewer.tsx` line 128

```ts
const instance = dayjs(date || new Date());
```

`date || new Date()` substitutes `new Date()` (current time) for any falsy `date`, including the integer `0`. A data column storing Unix epoch millisecond timestamps would render `0` (1970-01-01) as today's date. `date ?? new Date()` (nullish coalescing) would restrict the fallback to `null`/`undefined` only.

If this was intentional to match the original `just-handlebars-helpers`/moment behavior, a brief comment saying so avoids a future surprised reader changing it.

---

**NIT — No unit tests for helper edge cases**

The E2E spec rationale (bundling artifact, requires a real browser) is sound for the main regression. But the helper's edge-case behavior — invalid date strings producing `"Invalid date"`, empty `formatString`, the locale fallback documented above — can be exercised by calling `Handlebars.helpers.formatDate` directly in Jest without any bundling step. A small unit test file alongside `HandlebarsViewer.tsx` would guard these without requiring CI's browser environment.

---

### Automated scan coverage (TypeScript files — Python scans N/A)

This PR touches no Python files. The 20 Python-targeted scans (inline imports, SQL injection, RLS bypass, missing `@protect`, etc.) do not apply. TypeScript-relevant checks run above: no `any` types introduced in source (the existing `data: any` on `HandlebarsViewerProps` is pre-existing), no new dependencies added, dayjs plugin registration confirmed done before use via `extendedDayjs` import.

### Bundle size

No new runtime dependencies. `dayjs` is already a peer dependency. The override adds ~5 lines of helper code; no measurable size impact.

File: superset-frontend/plugins/plugin-chart-handlebars/src/components/Handlebars/HandlebarsViewer.tsx [hunk 12]
```diff
@@ -116,3 +116,19 @@ Handlebars.registerHelper('parseJson', (jsonString: string) => {
...
+
+// `just-handlebars-helpers` registers a `formatDate` helper that lazily
+// resolves `moment` via `global.moment` / `require('moment/min/moment-with-locales')`.
+// The bundled viewer switched to dayjs and never satisfies that lookup, so the
+// original helper throws "... is not a function" (see #32960). Re-register a
+// dayjs-backed `formatDate` with the same `{{formatDate formatString date [locale]}}`
+// signature so existing templates keep rendering.
+Handlebars.registerHelper('formatDate', (formatString, date, localeString) => {
+  const format = typeof formatString === 'string' ? formatString : '';
+  const instance = dayjs(date || new Date());
```
[the remark this answers is not in the document]
Comment (rusackas) [reply superset-frontend/plugins/plugin-chart-handlebars/src/components/Handlebars/HandlebarsViewer.tsx]: Good catch, epoch 0 would get clobbered. Switched to `date ?? new Date()`.

**Comment by rusackas** [comment]
@aminghadersohi thanks for the thorough look. Fixed the `||` → `??` so epoch `0` survives.

The locale one's a fair point - `extendedDayjs` only loads `en`, so `.locale('fr')` quietly no-ops. I'm a little torn on whether to throw vs just document it... throwing feels harsh for a template helper. Leaning toward a comment for now, but curious what you'd prefer?

**Review by aminghadersohi — COMMENTED** [review]
**Follow-up @ 0f4d0adc** (delta from 4ca1d338)

**LOW resolved** — `date ?? new Date()` (commit 0f4d0adc) correctly gates the fallback on `null`/`undefined` only; epoch-0 timestamps now format as 1970-01-01 as expected.

**MEDIUM still open** — `HandlebarsViewer.tsx:132`: `instance.locale(localeString)` silently falls back to English for any non-English locale. dayjs requires the locale module to be pre-imported before `.locale()` takes effect; `extendedDayjs` loads only English. A template author passing `'fr'` or `'de'` as the third argument gets English output with no error. Either document the English-only constraint in the block comment above the helper, or throw explicitly when the locale string is not `'en'`.

**NIT still open** — no unit tests for helper edge cases (invalid date → `"Invalid date"`, empty format string, locale fallback). Can be exercised in Jest by importing the module and calling `Handlebars.helpers.formatDate` directly.

**Comment by rusackas** [comment]
@aminghadersohi went with documenting the `en`-only locale behavior right at the call site rather than throwing, since a hard error felt heavy for a template helper. Also added the Jest edge-case tests you suggested (invalid date, non-string format, epoch-0, unloaded locale).

Separately, the playwright failure turned out to be a test bug of mine: `HTML_SANITIZATION` strips the `class` attribute, so `li.hb-item` never matched even though the dates rendered fine. Switched the assertion to plain `li`.

**Review by aminghadersohi — APPROVED** [review]
