### PR TITLE
fix: upgrade Flask-Caching>=1.10.0

### LINKED ISSUE #15258: documented data cache config doesn't work with flask-caching v1.9.0
I've following the guide [here](https://superset.apache.org/docs/installation/cache) to setup Redis as data cache with superset from master branch. 

### Expected results

Superset should work as it was without data cache configuration.

### Actual results

None of the chart works in any dashboards. While if clicking _Force Refresh_ option of a chart then it works again but still doesn't work when refreshing the whole dashboard.

#### Screenshots

Screenshot from 2021-06-18 10-56-22

#### How to reproduce the bug

1. Go to any dashboard
2. See error message `'Flask' object has no attribute 'get'`

### Environment

(please complete the following information):

- superset version: `Version: 0.999.0dev`
- python version: `3.7.9`

the stacktrace from webserver log:

```
10.0.2.100 - - [18/Jun/2021:13:42:00 +0000] "POST /api/v1/chart/data?form_data=%7B%22slice_id%22%3A62%7D&dashboard_id=2 HTTP/1.1" 500 236 "http://localhost:8088/superset/dashboard/births/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"
'Flask' object has no attribute 'get'
Traceback (most recent call last):
  File "/app/superset/views/base.py", line 204, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 228, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/utils/cache.py", line 159, in wrapper
    return f(*args, **kwargs)
  File "/app/superset/views/utils.py", line 470, in wrapper
    return f(*args, **kwargs)
  File "/app/superset/views/core.py", line 634, in explore_json
    return self.generate_json(viz_obj, response_type)
  File "/app/superset/views/core.py", line 454, in generate_json
    payload = viz_obj.get_payload()
  File "/app/superset/viz.py", line 450, in get_payload
    payload = self.get_df_payload(query_obj)
  File "/app/superset/viz.py", line 500, in get_df_payload
    cache_value = cache_manager.data_cache.get(cache_key)
  File "/usr/local/lib/python3.7/site-packages/flask_caching/__init__.py", line 248, in get
    return self.cache.get(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_caching/backends/rediscache.py", line 114, in get
    self._read_clients.get(self._get_prefix() + key)
AttributeError: 'Flask' object has no attribute 'get'
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by shawnzhu**
### SUMMARY
Fixes #15258 

### ADDITIONAL INFORMATION

- [x] Has associated issue: #15258 
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by shawnzhu** [comment]
Please advise if it needs a unit test since it uses `CACHE_TYPE: 'simple'` the current cache_tests:

https://github.com/apache/superset/blob/2cf99467fc49e9a99045215544bf92982655cdb0/tests/cache_tests.py#L68

**Review by betodealmeida — APPROVED** [review]
Thanks for fixing this!
