### PR TITLE
fix: Security manager incorrect calls

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
While testing 4.1 migrations, I noticed that the return types of the security manager calls were not being correctly validated by the IDE. To fix this, I added a type hint to our proxy definition and was able to find and fix problems in the code.

### TESTING INSTRUCTIONS
CI should be sufficient.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset/databases/api.py [hunk 1]
```diff
@@ -2274,6 +2274,6 @@ def schemas_access_for_file_upload(self, pk: int) -> Response:
         # otherwise the database should have been filtered out
         # in CsvToDatabaseForm
         schemas_allowed_processed = security_manager.get_schemas_accessible_by_user(
-            database, schemas_allowed, True
+            database, None, schemas_allowed, True
```
Comment (michael-s-molina) [inline superset/databases/api.py:2277]: This was a problem introduced with the catalog feature. @betodealmeida let me know if `None` is correct in this context or how we should get the catalog.

**Comment by michael-s-molina** [comment]
@betodealmeida @villebro @hughhhh Could you help me fix the following errors?

```
superset/models/helpers.py:824: error: Argument 1 to "get_rls_filters" of "SupersetSecurityManager" 
has incompatible type "ExploreMixin"; expected "BaseDatasource"  [arg-type]

superset/models/helpers.py:834: error: Argument 1 to "get_guest_rls_filters" of "SupersetSecurityManager" 
has incompatible type "ExploreMixin"; expected "BaseDatasource"  [arg-type]
```

This the signature of the methods:

```
def get_rls_filters(self, table: "BaseDatasource") -> list[SqlaQuery]:

def get_guest_rls_filters(self, dataset: "BaseDatasource") -> list[GuestTokenRlsRule]:
```

The calls to the security manager methods were introduced by https://github.com/apache/superset/pull/22853 and it seems that we already needed to pass `table` and `dataset` at that time but we never did. Do you know where to get them from?

**Comment by villebro** [comment]
Changes look good to me, but @betodealmeida and @hughhhh are probably best positioned to comment on the open questions here.

File: superset/databases/api.py (hunk 1 above)
Comment (betodealmeida) [reply superset/databases/api.py:2277]: Ah, yeah, we need to implement support for catalogs in the CSV upload feature.

Every time you need a catalog in a function and one is not explicitly passed you should use `database.get_default_catalog()` — it will return `None` for databases that don't support catalogs, and the default catalog for those that do.

In this case, we need to pass `database.get_default_catalog()` to `get_schemas_accessible_by_user`, otherwise the permissions check won't match if the database supports catalogs.

**Comment by betodealmeida** [comment]
For the type error, I think the current `get_sqla_row_level_filters` method should be moved out of `ExploreMixin` and into `BaseDatasource`, since only datasets can have RLS filters associarted with them (while a `Query` can't). We might need to leave a no-op method in the `ExploreMixin`, since I assume when building a chart from a query the method will get called.

@hughhhh does this seem right to you?

File: superset/security/manager.py [hunk 2]
```diff
@@ -2645,7 +2645,7 @@ def has_guest_access(self, dashboard: "Dashboard") -> bool:
         dashboards = [
             r
             for r in user.resources
-            if r["type"] == GuestTokenResourceType.DASHBOARD.value
+            if r["type"] == GuestTokenResourceType.DASHBOARD
```
Comment (michael-s-molina) [inline superset/security/manager.py:2648]: @betodealmeida @sadpandajoe This have the potential to break current security checks but it's the correct comparison for the defined type. Let me know if it's ok or if we should change the type to `str` instead.

**Comment by michael-s-molina** [comment]
@betodealmeida I think I addressed all your comments.

File: superset/extensions/__init__.py [hunk 3]
```diff
@@ -132,7 +133,7 @@ def init_app(self, app: Flask) -> None:
 migrate = Migrate()
 profiling = ProfilingExtension()
 results_backend_manager = ResultsBackendManager()
-security_manager = LocalProxy(lambda: appbuilder.sm)
+security_manager: SupersetSecurityManager = LocalProxy(lambda: appbuilder.sm)
```
Comment (dpgaspar) [inline superset/extensions/__init__.py:136]: nice this will help the IDE a lot!

**Review by dpgaspar — APPROVED** [review]
thank you for doing this
