### ISSUE TITLE
Save as dashboard with duplicating charts is not working after 1.4.0 upgrade

### ISSUE THREAD

**Issue by iercan** [apache/superset#18220]
After upgrading to 1.4.0 we are not able to save as a dashboard with duplicate chart option. This is the error shown in the logs. It gives the same error on all dashboards I tried. 

> superset_1  | 'NoneType' object has no attribute 'roles'
superset_1  | Traceback (most recent call last):
superset_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
superset_1  |     rv = self.dispatch_request()
superset_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
superset_1  |     return self.view_functions[rule.endpoint](**req.view_args)
superset_1  |   File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 148, in wraps
superset_1  |     return f(self, *args, **kwargs)
superset_1  |   File "/app/superset/utils/log.py", line 240, in wrapper
superset_1  |     value = f(*args, add_extra_log_payload=log, **kwargs)
superset_1  |   File "/app/superset/utils/decorators.py", line 104, in wrapper
superset_1  |     raise exception
superset_1  |   File "/app/superset/utils/decorators.py", line 100, in wrapper
superset_1  |     current_app.appbuilder.sm.raise_for_dashboard_access(dashboard)
superset_1  |   File "/app/superset/security/manager.py", line 1180, in raise_for_dashboard_access
superset_1  |     for dashboard_role in dashboard.roles
superset_1  | AttributeError: 'NoneType' object has no attribute 'roles'
superset_1  | 2022-01-28 21:10:43,139:ERROR:superset.views.base:'NoneType' object has no attribute 'roles'
superset_1  | Traceback (most recent call last):
superset_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
superset_1  |     rv = self.dispatch_request()
superset_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
superset_1  |     return self.view_functions[rule.endpoint](**req.view_args)
superset_1  |   File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 148, in wraps
superset_1  |     return f(self, *args, **kwargs)
superset_1  |   File "/app/superset/utils/log.py", line 240, in wrapper
superset_1  |     value = f(*args, add_extra_log_payload=log, **kwargs)
superset_1  |   File "/app/superset/utils/decorators.py", line 104, in wrapper
superset_1  |     raise exception
superset_1  |   File "/app/superset/utils/decorators.py", line 100, in wrapper
superset_1  |     current_app.appbuilder.sm.raise_for_dashboard_access(dashboard)
superset_1  |   File "/app/superset/security/manager.py", line 1180, in raise_for_dashboard_access
superset_1  |     for dashboard_role in dashboard.roles
superset_1  | AttributeError: 'NoneType' object has no attribute 'roles'

#### How to reproduce the bug

1. Open a dashboard 
2. Click save as option
3. Choose duplicate charts and save

### Expected results

New dashboard should be created by duplicating charts 

### Actual results

Process fails

### Environment

(please complete the following information):

- browser type and version: chrome 97
- superset version: 1.4.0 deployed with official image

**Comment by rumbin** [comment]
Confirming this for our deployment.

**Comment by rumbin** [comment]
![image](https://user-images.githubusercontent.com/1220356/151944211-c073f45a-e152-4dde-95f9-1adebb29287f.png)

**Comment by geido** [comment]
I cannot reproduce on master

**Comment by iercan** [comment]
@geido Can you try it with dashboard_rbac feature flag enabled. I suspect it is related with it.

**Comment by rumbin** [comment]
We don't have dashboard_rbac enabled and still have the issue on v. 1.4.0

**Comment by rumbin** [comment]
I just tested it with 1.4.0 Docker image with all FEATURE_FLAGS unaltered, i.e., with only the defalut feature flags activated:
The issue is still present.

**Comment by rumbin** [comment]
If @geido cannot reproduce on master, it seems that there might a solution that could be cherry-picked from it?!

**Comment by iercan** [comment]
I've tested it on 1.4.1. Problem seems resolved.

**Comment by PowerDinosaur** [comment]
I'm having the same issue on 2.1.0
