### PR TITLE
fix(sql-lab): do not replace undefined schema with empty object

### LINKED ISSUE #19658: DB Engine error 1.5.0rc2
Getting DB Engine error on the while running the SQL.

2022-04-12 11:54:44,750:DEBUG:superset.stats_logger:[stats_logger] (incr) DatabaseRestApi.function_names.success
2022-04-12 11:54:44,750:DEBUG:superset.stats_logger:[stats_logger] (timing) DatabaseRestApi.function_names.time | 17.298333999860915 
2022-04-12 11:54:44,751:INFO:werkzeug:127.0.0.1 - - [12/Apr/2022 11:54:44] "GET /api/v1/database/2/function_names/ HTTP/1.1" 200 -
2022-04-12 11:54:44,752:DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: mssql+pymssql://Zebpay_developer:XXXXXXXXXX@z8tbkx0ebz.database.windows.net:1433/zebpayTestnet-db
2022-04-12 11:54:44,762:DEBUG:superset.stats_logger:[stats_logger] (incr) DatabaseRestApi.get_list.success
2022-04-12 11:54:44,762:DEBUG:superset.stats_logger:[stats_logger] (timing) DatabaseRestApi.get_list.time | 22.575500001039472 
2022-04-12 11:54:44,764:INFO:werkzeug:127.0.0.1 - - [12/Apr/2022 11:54:44] "GET /api/v1/database/?q=(filters:!((col:database_name,opr:ct,value:%27%27),(col:expose_in_sqllab,opr:eq,value:!t)),order_columns:database_name,order_direction:asc,page:0,page_size:100) HTTP/1.1" 200 -
2022-04-12 11:54:48,600:DEBUG:superset.stats_logger:[stats_logger] (incr) DatabaseRestApi.schemas.success
2022-04-12 11:54:48,600:DEBUG:superset.stats_logger:[stats_logger] (timing) DatabaseRestApi.schemas.time | 3859.7955830009596 
2022-04-12 11:54:48,601:INFO:werkzeug:127.0.0.1 - - [12/Apr/2022 11:54:48] "GET /api/v1/database/2/schemas/?q=(force:!f) HTTP/1.1" 200 -
2022-04-12 11:55:19,563:ERROR:superset.views.core:Failed to execute query 'with currency AS 
(
select 'INR' as cur
UNION 
select 'USD' as cur
)
select * from currency': The query record was not created as expected 
 Please contact an administrator for further assistance or try again.
2022-04-12 11:55:19,566:DEBUG:superset.stats_logger:[stats_logger] (incr) sql_json
2022-04-12 11:55:19,569:INFO:werkzeug:127.0.0.1 - - [12/Apr/2022 11:55:19] "POST /superset/sql_json/ HTTP/1.1" 500 -
2022-04-12 11:55:31,312:INFO:werkzeug:127.0.0.1 - - [12/Apr/2022 11:55:31] "GET /api/v1/me/ HTTP/1.1" 200 -
2022-04-12 11:55:31,321:INFO:werkzeug:127.0.0.1 - - [12/Apr/2022 11:55:31] "GET /api/v1/me/ HTTP/1.1" 200 -
2022-04-12 11:55:35,548:DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: postgresql+psycopg2://xxxxxxxx
2022-04-12 11:55:35,571:DEBUG:superset.stats_logger:[stats_logger] (incr) DatabaseRestApi.function_names.success
2022-04-12 11:55:35,571:DEBUG:superset.stats_logger:[stats_logger] (timing) DatabaseRestApi.function_names.time | 33.699666000757134 
2022-04-12 11:55:35,571:INFO:werkzeug:127.0.0.1 - - [12/Apr/2022 11:55:35] "GET /api/v1/database/3/function_names/ HTTP/1.1" 200 -
2022-04-12 11:55:35,574:DEBUG:superset.stats_logger:[stats_logger] (incr) DatabaseRestApi.get_list.success
2022-04-12 11:55:35,574:DEBUG:superset.stats_logger:[stats_logger] (timing) DatabaseRestApi.get_list.time | 33.9531249992433 
2022-04-12 11:55:35,576:INFO:werkzeug:127.0.0.1 - - [12/Apr/2022 11:55:35] "GET /api/v1/database/?q=(filters:!((col:database_name,opr:ct,value:%27%27),(col:expose_in_sqllab,opr:eq,value:!t)),order_columns:database_name,order_direction:asc,page:0,page_size:100) HTTP/1.1" 200 -
2022-04-12 11:55:36,821:DEBUG:superset.stats_logger:[stats_logger] (incr) DatabaseRestApi.schemas.success
2022-04-12 11:55:36,821:DEBUG:superset.stats_logger:[stats_logger] (timing) DatabaseRestApi.schemas.time | 1286.3558750013908 
2022-04-12 11:55:36,822:INFO:werkzeug:127.0.0.1 - - [12/Apr/2022 11:55:36] "GET /api/v1/database/3/schemas/?q=(force:!f) HTTP/1.1" 200 -
2022-04-12 11:55:41,656:DEBUG:superset.stats_logger:[stats_logger] (incr) validate_sql_json
2022-04-12 11:55:41,663:INFO:werkzeug:127.0.0.1 - - [12/Apr/2022 11:55:41] "POST /superset/validate_sql_json/ HTTP/1.1" 200 -
2022-04-12 11:55:43,148:DEBUG:superset.stats_logger:[stats_logger] (incr) validate_sql_json
2022-04-12 11:55:43,152:INFO:werkzeug:127.0.0.1 - - [12/Apr/2022 11:55:43] "POST /superset/validate_sql_json/ HTTP/1.1" 200 -
2022-04-12 11:55:43,503:DEBUG:superset.stats_logger:[stats_logger] (incr) extra_table_metadata
2022-04-12 11:55:43,503:DEBUG:superset.stats_logger:[stats_logger] (incr) DatabaseRestApi.table_metadata.init
2022-04-12 11:55:43,504:DEBUG:superset.models.core:Database.get_sqla_engine(). Masked URL: postgresql+psycopg2://xxxxx
2022-04-12 11:55:43,506:INFO:werkzeug:127.0.0.1 - - [12/Apr/2022 11:55:43] "GET /superset/extra_table_metadata/3/ab_role/%255Bobject%2520Object%255D/ HTTP/1.1" 200 -
2022-04-12 11:55:44,117:DEBUG:superset.stats_logger:[stats_logger] (incr) validate_sql_json
2022-04-12 11:55:44,121:INFO:werkzeug:127.0.0.1 - - [12/Apr/2022 11:55:44] "POST /superset/validate_sql_json/ HTTP/1.1" 200 -
2022-04-12 11:55:44,644:DEBUG:superset.stats_logger:[stats_logger] (incr) DatabaseRestApi.table_metadata.error
2022-04-12 11:55:44,650:DEBUG:superset.stats_logger:[stats_logger] (incr) DatabaseRestApi.table_metadata.error
2022-04-12 11:55:44,650:DEBUG:superset.stats_logger:[stats_logger] (timing) DatabaseRestApi.table_metadata.time | 1146.9648750007764 
2022-04-12 11:55:44,651:INFO:werkzeug:127.0.0.1 - - [12/Apr/2022 11:55:44] "GET /api/v1/database/3/table/ab_role/%255Bobject%2520Object%255D/ HTTP/1.1" 422 -
2022-04-12 11:55:44,774:INFO:superset.sqllab.command:Triggering query_id: 7
2022-04-12 11:55:44,777:DEBUG:superset.sql_parse:Parsing with sqlparse statement: None
2022-04-12 11:55:44,786:ERROR:superset.views.core:Failed to execute query '7' - 'None': 'NoneType' object has no attribute 'strip'
2022-04-12 11:55:44,787:DEBUG:superset.stats_logger:[stats_logger] (incr) sql_json
2022-04-12 11:55:44,789:INFO:werkzeug:127.0.0.1 - - [12/Apr/2022 11:55:44] "POST /superset/sql_json/ HTTP/1.1" 500 -
2022-04-12 11:55:45,631:ERROR:superset.views.core:Failed to execute query '
select * from ab_role ': The query record was not created as expected 
 Please contact an administrator for further assistance or try again.
2022-04-12 11:55:45,633:DEBUG:superset.stats_logger:[stats_logger] (incr) sql_json
2022-04-12 11:55:45,635:INFO:werkzeug:127.0.0.1 - - [12/Apr/2022 11:55:45] "POST /superset/sql_json/ HTTP/1.1" 500 -
2022-04-12 11:55:49,167:ERROR:superset.views.core:Failed to execute query 'select * from ab_role ': The query record was not created as expected 
 Please contact an administrator for further assistance or try again.
2022-04-12 11:55:49,169:DEBUG:superset.stats_logger:[stats_logger] (incr) sql_json
2022-04-12 11:55:49,171:INFO:werkzeug:127.0.0.1 - - [12/Apr/2022 11:55:49] "POST /superset/sql_json/ HTTP/1.1" 500 -

#### Screenshots

image

### Environment

- superset version: `1.5.0rc2`

### How to reproduce this error

- Create new database connection
- Query any table/view from the database by only selecting the database from the SQLLab
- Don't select schema and see table schema. 
- In the above situation you will get the DB Engine error mentioned in the screenshot.

### PR DESCRIPTION
**Pull request by villebro**
### SUMMARY
In a change introduced in #18609, SQL Lab incorrectly replaces a missing schema with an empty object when dispatching the query action, which causes the query to fail in the backend, which later breaks the whole UI and makes it impossible to enter SQL Lab again.

See a few examples of what a valid schema is in this context:
https://github.com/apache/superset/blob/3a231f6b871cdab00b9dfb6192af76cf4cf9832a/superset-frontend/src/SqlLab/components/SqlEditorLeftBar/index.tsx#L42
https://github.com/apache/superset/blob/3a231f6b871cdab00b9dfb6192af76cf4cf9832a/superset-frontend/src/components/DatabaseSelector/index.tsx#L96
https://github.com/apache/superset/blob/3a231f6b871cdab00b9dfb6192af76cf4cf9832a/superset-frontend/src/components/DatabaseSelector/index.tsx#L99

### AFTER
Now SQL Lab executes correctly even when not selecting a schema:
image

### BEFORE
Previously the schema would fail to execute due to the empty object not being compatible with the column type in the metastore:
image

### ADDITIONAL INFORMATION

- [x] Has associated issue: closes #19658
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by zhaoyongjie — APPROVED** [review]
LGTM

**Review by kgabryje — COMMENTED** [review]
lgtm!
