### PR TITLE
fix(dashboard): required filters reliably apply default + Apply enables on change

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY

Fixes a regression where required filters with default values intermittently fail to apply on dashboard load, and the **Apply Filters** button becomes unresponsive even after the user manually enters a value.

**Three independent code paths that produce overlapping symptoms — fixed all three:**

1. **`FilterBar/utils.ts:checkIsApplyDisabled`** — regression from #37681. The early-return `if (selectedCount !== appliedCount) return true` disabled Apply whenever Selected had an entry Applied lacked. That is exactly what happens when a user types a value into a filter whose default never made it into Applied. Removed the early return; `dataEqual` with `ignoreUndefined: true` already handles the "no real change" case correctly via lodash `omitBy(v => v === undefined)`.

2. **`dataMask/reducer.ts:updateDataMaskForFilterChanges`** — when a required filter (`enableEmptyFilter=true` or `defaultToFirstItem=true`) was modified, the existing `filterState`/`extraFormData` was preserved even when empty, silently wiping a newly defined default. Added a `hasExistingValue` guard so empty state cannot override a real default. Matches the customer's "easier to reproduce after modifying required filter configurations" cue.

3. **`dataMask/reducer.ts:fillNativeFilters`** — on `HYDRATE_DASHBOARD`, the shallow spread of the permalink-loaded `dataMask` over `filter.defaultDataMask` wiped the default when the loaded mask was captured mid-initialization (e.g. permalink generated before filters fully populated). Now, **for required filters only**, we restore `filterState`/`extraFormData` from `defaultDataMask` when the loaded mask carries no real value. Non-required filters keep current behavior so an explicit user-clear isn't undone.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

N/A — internal state behavior. Reported pattern from the customer:
- Required filter loads empty (or value visible but charts unfiltered).
- User types a value → **Apply Filters** stays disabled.
- After this fix, both paths are corrected.

### TESTING INSTRUCTIONS

Existing unit + integration tests pass (58 tests across `utils.test.ts`, `reducer.test.ts`, `FilterBar.test.tsx`). One test that locked in the buggy "count mismatch disables Apply" behavior was updated to assert the corrected behavior.

**Manual repro (recommended, since the bug is timing-sensitive)**:

1. Open the **Sales dashboard** in Examples.
2. Configure a filter with both **Filter value is required** and **Filter has default value** enabled.
3. Reload the dashboard a few times. Confirm:
   - Default value is pre-filled.
   - Charts render filtered (no unfiltered queries).
4. Click into a chart, then navigate back to the dashboard. Repeat step 3 — defaults must survive the permalink rehydration.
5. Modify the filter configuration (change default, save). Confirm the new default appears and applies.
6. In a scenario where the default was missing (pre-fix), type a value manually. Confirm **Apply Filters** becomes enabled.

**Test plan** (CI):

- [ ] `npm run test` in `superset-frontend` — all FilterBar / dataMask suites green.
- [ ] Manual QA on a test env walking through the steps above.
- [ ] Confirm no regression in Clear All behavior (`FilterBar.test.tsx` covers this — 21/21 pass).

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

**Open items / caveats**:

- Symptom (b) — "default present in UI but not applied to charts" — is partly governed by the `needsAutoApply` logic in `FilterBar/index.tsx:237-253` (untouched). My three fixes target three distinct root causes; if a fourth remains, it would manifest here. Manual QA on the test env will confirm.
- New regression tests for each fix path (modify-config preserves default, permalink rehydration preserves default) are deferred per the original direction — happy to add after manual QA validates the fix shape.

### CODE REVIEW

File: superset-frontend/src/dataMask/reducer.ts [hunk 1]
```diff
@@ -155,12 +197,24 @@ function updateDataMaskForFilterChanges(
...
+    // newly-defined) default. defaultToFirstItem filters keep the old behavior:
+    // FilterValue re-resolves the first item at runtime, so preserving the
+    // mid-init empty state is fine.
+    const isRequired = !!filter.controlValues?.enableEmptyFilter;
+    const isFirstItem = !!filter.controlValues?.defaultToFirstItem;
+    const existingValue = existingFilter?.filterState?.value;
+    const hasExistingValue =
+      existingValue !== undefined &&
+      existingValue !== null &&
+      !(Array.isArray(existingValue) && existingValue.length === 0);
```
Comment (msyavuz) [inline superset-frontend/src/dataMask/reducer.ts]: [null, null] is true for this right? But we set it as such in 

```
    const loadedHasValue =
      loadedValue !== undefined &&
      loadedValue !== null &&
      !(
        // Treat all-null arrays (range filters use [null, null] as their
        // canonical cleared value) and empty arrays as "no value".
        Array.isArray(loadedValue) && loadedValue.every(v => v === null)
      );
```
Is this a problem?

Comment (geido) [reply superset-frontend/src/dataMask/reducer.ts]: Good catch — yes, that was an inconsistency. `fillNativeFilters` treated an all-null array (`[null, null]`, a range filter's canonical cleared value) as "no value", but `hasExistingValue` here only checked for an *empty* array. So a required range filter cleared to `[null, null]` would be considered to "have a value", its empty state would be preserved, and a newly-defined default would get wiped — exactly the bug this PR is fixing.

Fixed in de4b75cbc8 by mirroring `loadedHasValue`:

```ts
!(Array.isArray(existingValue) && existingValue.every(v => v === null));
```

`[].every()` is `true`, so the empty-array case is still covered (and oxlint's `no-useless-length-check` stays satisfied). Added a regression test that fails on the old logic (`Received [null, null]`, expected the new default) and passes now.

File: superset-frontend/src/dataMask/reducer.ts [hunk 2]
```diff
@@ -109,10 +109,50 @@ function fillNativeFilters(
...
+    // isn't undone.
+    const isRequired = !!filter.controlValues?.enableEmptyFilter;
+    const loadedValue = loaded?.filterState?.value;
+    const loadedHasValue =
+      loadedValue !== undefined &&
+      loadedValue !== null &&
+      !(
+        // Treat all-null arrays (range filters use [null, null] as their
+        // canonical cleared value) and empty arrays as "no value".
+        (Array.isArray(loadedValue) && loadedValue.every(v => v === null))
```
[the remark this answers is not in the document]
Comment (geido) [reply superset-frontend/src/dataMask/reducer.ts:129]: This is a false positive. The `length === 0` check was removed because it's redundant: `[].every(v => v === null)` returns `true` (vacuous truth), so `Array.isArray(loadedValue) && loadedValue.every(v => v === null)` already evaluates to `true` for an empty array — empty arrays are still treated as "no value" and `shouldRestoreDefault` still fires for required filters.

Re-adding `loadedValue.length === 0 ||` would re-introduce the `oxlint unicorn/no-useless-length-check` error that's currently failing CI on this file, so I'm not applying the suggestion. (Bito's own top-level reply above already concluded "the logic is correct.")

**Review by msyavuz — APPROVED** [review]
