### PR TITLE
fix(sqllab): SqlJsonExecutionContext.query null pointer

### PR DESCRIPTION
**Pull request by serenajiang**
### SUMMARY
Users saw this error when their sqllab queries failed due to access errors:
`'SqlJsonExecutionContext' object has no attribute 'query'`

The issue is that `_validate_access` is run before `set_query`, so the `execution_context` does not have a `query` attribute during `_validate_access`, which may throw an exception that uses query details to generate an error message. This was likely a regression caused by #16852.

I am not very satisfied with this fix - `SqlJsonExecutionContext` should probably always have a `query` attribute since it's a dataclass? But I'm not sure what the intended behavior is, so input is welcome.

@ofekisr @etr2460

### CODE REVIEW

**Review by etr2460 — APPROVED** [review]
ehh, i think this is fine. It's only for getting query details anyway

**Comment by AAfghahi** [comment]
🏷 v1.4
