### PR TITLE
fix: table quoting in DBs with `supports_cross_catalog_queries=True`

### LINKED ISSUE #35116: Physical dataset SQL compilation error in charts, due to incorrect quoting (Snowflake, Superset 6.0.0rc1)
### Bug description

**Observed:**

When a **physical** dataset is created and subsequently used in a chart, the following error is raised when trying to render the chart:

```
SQL compilation error: Object '"my_db.my_schema.my_table"' does not exist or not authorized.
```

**Expected:**

Chart renders.

**Notes:**

Connection string, privileges and table/schema/database names are all set up correctly. Apparently, this is due to the table reference being incorrectly quoted as a single identifier in the generated query for a chart with a physical dataset:
```sql
SELECT
  DATE_TRUNC('DAY', "ROW_INSERTED_TIME") AS "ROW_INSERTED_TIME",
  COUNT(*) AS "count"
FROM "my_db.my_schema.my_table"
GROUP BY
  DATE_TRUNC('DAY', "ROW_INSERTED_TIME")
ORDER BY
  "count" DESC
LIMIT 10000
```

If I create a **virtual** dataset on that exact Snowflake table, with the exact same database connection, it works as expected (since SQL Lab allows me to specify the table reference w/o any quotes): the chart renders, and the generated query looks like this:
```sql
SELECT
  DATE_TRUNC('DAY', "ROW_INSERTED_TIME") AS "ROW_INSERTED_TIME",
  COUNT(*) AS "count"
FROM (
  SELECT
    *
  FROM my_db.my_schema.my_table
) AS virtual_table
GROUP BY
  DATE_TRUNC('DAY', "ROW_INSERTED_TIME")
ORDER BY
  "count" DESC
LIMIT 10000
```

### Screenshots/recordings

_No response_

### Superset version

master / latest-dev

### Python version

3.11

### Node version

Not applicable

### Browser

Chrome

### Additional context

superset 6.0.0rc1
snowflake-sqlalchemy==1.7.6, 1.7.7 (latest - tested with both versions, same results)

The only somewhat similar issue that I found, is https://github.com/apache/superset/issues/34996 (a different engine - Doris vs. this is on Snowflake - hinting that this might be a bug in Superset or one of its dependencies, that is not specific to a single engine spec). 

Also, I have a report from a coworker who tried using an older version of Superset with Snowflake, and didn't observe any issues while using physical datasets - so assuming this may be a regression in 6.0.0.

```
WARNING:superset.connectors.sqla.models:Query SELECT DATE_TRUNC('DAY', "ROW_INSERTED_TIME") AS "ROW_INSERTED_TIME", COUNT(*) AS "count" 
FROM "my_db.my_schema.my_table" GROUP BY DATE_TRUNC('DAY', "ROW_INSERTED_TIME") ORDER BY "count" DESC
LIMIT 10000 on schema my_schema failed
Traceback (most recent call last): 
File "/app/superset/connectors/sqla/models.py", line 1593, in query
df = self.database.get_df(
^^^^^^^^^^^^^^^^^^^^^ 
File "/app/superset/models/core.py", line 705, in get_df
self.db_engine_spec.execute(cursor, sql_, self) 
File "/app/superset/db_engine_specs/base.py", line 1853, in execute 
raise cls.get_dbapi_mapped_exception(ex) from ex 
File "/app/superset/db_engine_specs/base.py", line 1849, in execute 
cursor.execute(query) 
File "/app/.venv/lib/python3.11/site-packages/snowflake/connector/cursor.py", line 1134, in execute
Error.errorhandler_wrapper(self.connection, self, error_class, errvalue) 
File "/app/.venv/lib/python3.11/site-packages/snowflake/connector/errors.py", line 286, in errorhandler_wrapper 
handed_over = Error.hand_to_other_handler(
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/app/.venv/lib/python3.11/site-packages/snowflake/connector/errors.py", line 341, in hand_to_other_handler
cursor.errorhandler(connection, cursor, error_class, error_value)
File "/app/.venv/lib/python3.11/site-packages/snowflake/connector/errors.py", line 217, in default_errorhandler
raise error_class( 
snowflake.connector.errors.ProgrammingError: 002003 (42S02): 01bf0031-0811-88a3-0002-21017995f1db: SQL compilation error: 
Object '"my_db.my_schema.my_table"' does not exist or not authorized.
```

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### LINKED ISSUE #35910: Trino charts fails after upgrading 6.0.0rc2
### Bug description

I'm testing 6.0.0rc2

After upgrading to 6.0.0rc2, several charts using the Trino Mongo connector encounter below error. Seems it incorrectly generate the table schema by adding "mongodb.waplog2" twice to the table name. This issue occurs only with physical datasets, while virtual datasets function correctly.

```
Data error
Error: TrinoUserError(type=USER_ERROR, name=TABLE_NOT_FOUND, message="line 4:6: Table 'mongodb.waplog2."mongodb.waplog2.livejoy_how_did_you_hear_us"' does not exist", query_id=20251030_145628_00742_n5t7m)
```

### Screenshots/recordings

_No response_

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by betodealmeida**
### SUMMARY

Fix for https://github.com/apache/superset/issues/35116: when DBs have `supports_cross_catalog_queries=True` the table name is being incorrectly quoted.

### TESTING INSTRUCTIONS

Added unit tests.

### ADDITIONAL INFORMATION

- [X] Has associated issue: 
   - Fixes #35116
   - Fixes #35910 
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by aminghadersohi — APPROVED** [review]
perfect

**Review by rusackas — APPROVED** [review]
LGTM! Don't forget to give the bots some 👍 👎 feedback so they can do better ;)
