### PR TITLE
[sqllab] fix unexpected keyword argument 'ignore_nan'

### PR DESCRIPTION
**Pull request by mistercrunch**
fixes issue introduced by https://github.com/apache/incubator-superset/pull/5413
@john-bodley @timifasubaa

### CODE REVIEW

**Review by betodealmeida — APPROVED** [review]
It would be good to standardize on always using `simplejson` instead of `json`, I noticed we use both. The former also has the advantage that it produces strict JSON compared to the latter.
