### PR TITLE
fix(semantic-layers): separate grain and offset time-axis resolvers

### LINKED ISSUE #42092: fix(semantic-layers): consolidate duplicate time-axis helper and tests
### Bug description

`master` defines `_get_time_axis_column` twice in `superset/semantic_layers/mapper.py` and repeats several test function names in `tests/unit_tests/semantic_layers/mapper_test.py`.

The first helper was introduced by #41556 for time-comparison `TEMPORAL_RANGE` handling. The second was introduced later by #41456 for SemanticView time-grain selection:

- First definition: https://github.com/apache/superset/blob/c6da740ce2/superset/semantic_layers/mapper.py#L515-L565
- Second definition: https://github.com/apache/superset/blob/c6da740ce2/superset/semantic_layers/mapper.py#L1040-L1082
- Earlier duplicate-named tests: https://github.com/apache/superset/blob/c6da740ce2/tests/unit_tests/semantic_layers/mapper_test.py#L1283
- Later duplicate-named tests: https://github.com/apache/superset/blob/c6da740ce2/tests/unit_tests/semantic_layers/mapper_test.py#L3662

Python silently replaces the first helper with the second at module import time. Pytest likewise replaces duplicate module-level test functions before collection. As a result, the earlier temporal-filter fallback behavior and its tests can be hidden rather than composed with the later time-grain behavior.

Reproduction:

1. Check out current `master`.
2. Run `pre-commit run mypy --all-files` or `pre-commit run --all-files`.
3. Observe:

```text
superset/semantic_layers/mapper.py:1040: error: Name "_get_time_axis_column" already defined on line 515  [no-redef]
tests/unit_tests/semantic_layers/mapper_test.py:3662: error: Name "test_get_time_axis_column_returns_granularity_when_set" already defined on line 1283  [no-redef]
tests/unit_tests/semantic_layers/mapper_test.py:3671: error: Name "test_get_time_axis_column_finds_temporal_in_columns" already defined on line 1292  [no-redef]
tests/unit_tests/semantic_layers/mapper_test.py:3774: error: Name "test_get_time_axis_column_skips_unparseable_adhoc_columns" already defined on line 1335  [no-redef]
```

Expected behavior: one helper should deliberately combine the temporal-range fallback from #41556 with the unambiguous time-axis selection required by #41456, and each behavior should have uniquely named, collected tests.

### Environment

- Superset version: master / latest-dev
- Python version: local verification used Python 3.12
- Node version: not applicable
- Browser: not applicable

### Additional context

This was discovered while running the mandatory all-files pre-commit gate for an unrelated backend change. The same duplicate definitions are present on `origin/master`; they are not part of that feature branch.

### Checklist

- [x] I searched the GitHub issue tracker and did not find a similar bug report.
- [x] I included the relevant MyPy output and exact source locations.
- [x] This is not a security report.

### PR DESCRIPTION
**Pull request by sadpandajoe**
### SUMMARY

`superset/semantic_layers/mapper.py` defined `_get_time_axis_column` twice, with deliberately different semantics:

- **offset resolver** (defined first): returns the first temporal column, falling back to the column named in a `TEMPORAL_RANGE` adhoc filter, so aggregate-only charts that carry the temporal column only in a filter still get offset-aware time bounds. Used by `_get_time_filter` and `_get_group_limit_filters`.
- **grain resolver** (defined later): only claims an axis when the selected columns contain exactly one temporal dimension, otherwise returns `None` so the grain path falls back to raw variants instead of guessing. Used by `map_query_object` and `_validate_granularity`.

Because both shared the name `_get_time_axis_column`, the second definition shadowed the first. Two consequences:

1. **mypy failed pre-commit** — `Name "_get_time_axis_column" already defined [no-redef]` — turning the branch red.
2. **Silent regression**: the offset call sites resolved to the grain function at runtime, so the time offset / time-comparison bounds were dropped for aggregate-only charts whose temporal column lives only in a `TEMPORAL_RANGE` filter. The unit test covering that path was already failing but stayed hidden because an unrelated Python 3.10 CI leg errored out first and cancelled the sibling jobs.

This PR renames the grain resolver to `_get_grain_time_axis_column` and points its call sites (`map_query_object`, `_validate_granularity`) at it, leaving the offset resolver under the original name for its call sites. The two duplicated test blocks are reconciled so both resolvers are covered.

### TESTING INSTRUCTIONS

```
pytest tests/unit_tests/semantic_layers/mapper_test.py
```

185 tests pass. Before this change, `test_get_time_axis_column_finds_temporal_in_temporal_range_filter` failed (the masked regression) and `pre-commit run mypy` reported the `[no-redef]` error; both pass now.

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #42092
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

> **Note on red CI checks:** The failing **Python 3.10** unit/integration legs on this PR (and the resulting cancellation of the 3.11 / 3.12 legs) are a pre-existing `syntaqlite` / `StrEnum` incompatibility unrelated to this change, already tracked separately (#42007 / #42045 / #42058). This PR is intentionally scoped to the `mapper.py` regression above; the **pre-commit** check reflects the actual fix here.

### CODE REVIEW

**Review by mikebridge — APPROVED** [review]
fixes the naming conflict---lgtm

**Review by yousoph — APPROVED** [review]
