### ISSUE TITLE
superset 1.3.0 version code using the wrong sasl dependency version with its Python version 3.7 or 3.8

### ISSUE THREAD

**Issue by wyc990122** [apache/superset#22998]
#### How to reproduce the bug

1. Switch to the 1.3.0 tag of the superset code
2. Open the CONTRIBUTING.md file,and the 426 line says: "Ensure that you are using Python version 3.7 or 3.8, then proceed with"(Does it means that 1.3.0 superset works with Python 3.7 or 3.8?)
3. ![捕获](https://user-images.githubusercontent.com/65800480/216930699-10ba6453-27d5-4483-9871-7e56172155ba.PNG)
4. run pip install -r requirements/development.txt command in the fresh Python 3.7 environment(created by virtualenv in Pycharm)
5. Then the error occurs:
```
fatal error C1083: Cannot open include file: 'sasl/sasl.h': 
No such file or directory error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2
```
6. Edit the file requirements/development.txt,change sasl==0.2.1 to sasl==0.3.1,then pip install again and the error is fixed.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `1.3.0`
- python version: `3.7`
- node.js version: unknown
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [✔] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [❌] I have reproduced the issue with at least the latest released version of superset.
- [✔] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I'll leave this open for a moment in case anyone has suggestions, but it seems there are a couple of troublesome things going on that will make this issue difficult to deal with:
1) It looks like you're running Superset on Windows. A few people do this, but it's not officially supported, and typically takes some hacking to get it to work.
2) You're using superset 1.3! This is also no longer supported. The community is currently on 2.0.1, and there's LTS support (i.e. security patches) for 1.5.x. Is there any reason to use the old version?
