### ISSUE TITLE
athena: module 'sqlalchemy.types' has no attribute 'DOUBLE'

### ISSUE THREAD

**Issue by jgournet** [apache/superset#27559]
### Bug description

Hi every one,

I'm facing an issue when try to connect with Athena using PyAthena with the connection string (SQLALCHEMY URI):

awsathena+rest://{aws_access_key_id}:{aws_secret_access_key}@athena.{region_name}.amazonaws.com/{schema_name}?s3_staging_dir={s3_staging_dir}

It's prompt this error in docker logs:

superset.commands.database.exceptions.DatabaseTestConnectionUnexpectedError: [SupersetError(message="module 'sqlalchemy.types' has no attribute 'DOUBLE'", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Amazon Athena', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]

Note:
creating a ticket from discussion https://github.com/apache/superset/discussions/27543

### How to reproduce the bug

We do not have enough knowledge of the cause of this bug.

This might help ?:
This error does NOT occur when running superset from an image created as of the 9th of March from superset:latest image.
But our new image, based on superset:latest as of 16th of March gets this error.

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

(issue has been reported on slack too, on 18th of March)

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
> It worked with PyAthena 3.0.0 version. The latest version of PyAthena seems to have problem.

This comment was on the discussion - if that's true, then (a) can you downgrade PyAthena to resolve this issue, and (b) have you considered looking into whether or not anyone's filed a bug on the PyAthena side of the table?

**Comment by jgournet** [comment]
Looks like pyathena released 3.5.1 with a fix for this issue:
https://github.com/laughingman7743/PyAthena/releases/tag/v3.5.1
=> Closing this ticket
